version: '3.8'

services:
  app:
    build: .
    container_name: susanghanguys-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always

  redis:
    image: redis:7.2
    container_name: susanghanguys-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

volumes:
  redis-data: