name: '🐛 Bug Report Template'
description: '버그 리포트를 작성할 때 사용하는 템플릿입니다. 이슈는 Jira와 연동됩니다.'
title: 'fix: '
labels: ['🐛bug']

body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'PRJ-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명 (Branch)'
      description: '영어로 브랜치명을 작성해주세요'
      placeholder: 'fix/logout'
    validations:
      required: true

  - type: textarea
    id: bugSummary
    attributes:
      label: '🐛 어떤 버그인가요?'
      description: '문제가 되는 현상을 간략히 설명해주세요.'
      placeholder: '로그인 시 잘못된 비밀번호를 입력해도 오류 메시지가 표시되지 않음'
    validations:
        required: true

  - type: textarea
    id: reproductionSteps
    attributes:
      label: '🤷‍♂️ 재현 절차 (Reproduction Steps)'
      description: '가능하면 Given-When-Then 형식으로 작성해주세요.'
      placeholder: |
        예:
        Given: 사용자가 로그인 페이지에 접근함  
        When: 잘못된 비밀번호를 입력하고 로그인 버튼을 클릭함  
        Then: "비밀번호가 올바르지 않습니다" 라는 메시지가 출력되어야 함
    validations:
      required: true

  - type: textarea
    id: expectedResult
    attributes:
      label: '🤔 예상 결과 (Expected Result)'
      description: '정상적으로 작동할 경우 어떤 결과가 나와야 했는지 적어주세요.'
      placeholder: '"비밀번호가 올바르지 않습니다"라는 오류 메시지 출력'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 작업 항목 (Checklist)'
      description: '이 버그를 해결하기 위해 필요한 작업 목록을 작성해주세요.'
      value: |
        - [ ] 원인 분석
        - [ ] 코드 수정
        - [ ] 테스트 작성 및 수행
        - [ ] 배포 후 확인
    validations:
      required: true