name: '♻️ Refactor Template'
description: '리팩토링 작업 시 사용하는 템플릿입니다. 이슈는 Jira와 연동됩니다.'
title: 'refactor: '
labels: ['♻️refactor']

body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 티켓 번호 (Jira Ticket)'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'PRJ-789'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명 (Branch Name)'
      description: '영어로 브랜치명을 작성해주세요.'
      placeholder: 'refactor/payment-module'
    validations:
      required: true

  - type: textarea
    id: refactorTarget
    attributes:
      label: '📌 리팩토링 대상 기능'
      description: '어떤 기능을 리팩토링하는지 간결하게 설명해주세요.'
      placeholder: '결제 모듈 내 중복 로직 제거 및 가독성 개선'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '📝 작업 상세 내용'
      description: '리팩토링 과정에서 수행할 작업들을 구체적으로 작성해주세요.'
      value: |
        - [ ] 중복 함수 제거
        - [ ] 조건문 단순화
        - [ ] 변수명 명확하게 수정
    validations:
      required: true