name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - feat/#35-deploy-refactor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload deployment files
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: |
            build/libs/server-0.0.1-SNAPSHOT.jar
            Dockerfile
            docker-compose.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-files
          path: deployment

      - name: Deploy to EC2 using Docker
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Upload original JAR
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            deployment/server-0.0.1-SNAPSHOT.jar \
            $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/

          # Rename it to soosanghan.jar on the server
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "
            cd /home/$EC2_USERNAME/
            mv server-0.0.1-SNAPSHOT.jar soosanghan.jar
          "

          # Upload Dockerfile and docker-compose.yml
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            deployment/Dockerfile \
            deployment/docker-compose.yml \
            $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/

          # Restart Docker container
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "
            cd /home/$EC2_USERNAME/
            docker-compose down
            docker-compose up --build -d
          "

          rm -f private_key.pem